services:
  mongodb:
    image: mongo:6.0
    container_name: trivia-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=trivia-quiz
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trivia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trivia-backend
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/trivia-quiz
    restart: on-failure
    networks:
      - trivia-network

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: trivia-frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend
      environment:
        - VITE_API_URL=http://localhost:3001/api
        - VITE_GRAPHQL_URL=http://localhost:3001/graphql
      networks:
        - trivia-network

networks:
  trivia-network:
    name: trivia-network

volumes:
  mongodb_data:
    name: trivia-mongodb-data
