services:
  mongodb:
    image: mongo:latest
    container_name: trivia-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=trivia
    networks:
      - trivia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trivia-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/trivia
    networks:
      - trivia-network

networks:
  trivia-network:
    driver: bridge

volumes:
  mongodb_data:
